##################################################################################################
# +--------------------------------------------------------------------------------------------+ #
# |    _____  _            ___                  _    _                ___                      | #
# |   |_   _|| |_   ___   / __| ___  _  _  _ _ | |_ (_) _ _   __ _   / __| __ _  _ __   ___    | #
# |     | |  | ' \ / -_) | (__ / _ \| || || ' \|  _|| || ' \ / _` | | (_ |/ _` || '  \ / -_)   | #
# |     |_|  |_||_|\___|  \___|\___/ \_,_||_||_|\__||_||_||_|\__, |  \___|\__,_||_|_|_|\___|   | #
# |                                                          |___/                             | #
# | By: Benz56                                                                                 | #
# +--------------------------------------------------------------------------------------------+ #
##################################################################################################

# If no player has sent a correct count in x seconds the broadcaster will send an 'IdleBroadcast'
# message. How many seconds of game inactivity should pass before broadcasting said message?
#
# If the last message sent in chat is by the broadcaster it won't send a message again.
#
# Set this to -1 to disable the broadcaster entirely.
IdleBroadcast: 900

# By inverting the blacklist you're essentially creating a whitelist i.e. enabled worlds list.
# Use this if you have e.g. 10 worlds and only want to enable The Counting Game in one world.
# Instead of blacklisting 9 worlds you can invert the list and add the only enabled world.
InvertBlacklist: false

# A list of worlds where messages associated with The Counting Game won't be sent. This includes
# participating in the game. Players won't be able to send a number in a blacklisted world.
BlacklistedWorlds:
  #- world

# Update Checker.
# Enable or disable the update checker.
UpdateCheckerEnabled: true
# false: All OPs are notified of a new update when they join.
# true: OPs are only notified if they have the countinggame.update permission as well.
# N.B. any user with the countinggame.update permission is notified; OP or not.
UpdateCheckerPermissionOnly: false